CREATE TABLE booking_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  booking_id INT NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE
);
